Program message passing
interface (MPI) menggunakan python sesuai rancangan bagan pipeline yang telah dibuat.
Studi kasus MPI pada perekapan pengiriman dan penerimaan barang dan infrastruktur sekolah (sekolah dasar)

In [1]:
!mpiexec -n 21 python bcast_scatter_gather_reducearray.py

Pengiriman data barang dari rank 0 ke rank 2 dengan data :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Pengiriman data barang dari rank 0 ke rank 3 dengan data :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Rank 2 menerima data barang dari rank 0 dengan data :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Rank 3 menerima data barang dari rank 0 dengan data :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Rank 2 melakukan broadcast
Rank 3 melakukan broadcast
(bcast from root 2)-> Rank 3 data :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
(bcast from root 2)-> Rank 4 data :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Hasil Scatter 01
Rank 5 dengan data :  5
Hasil Scatter 01
Rank 6 dengan data :  6
Hasil Scatter 01
Rank 7 dengan data :  7
Hasil Scatter 01
Rank 8 dengan data :  8
Hasil Gather 01
Rank 9 dengan data :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,

In [2]:
!mpiexec -n 20 python mpihello.py

Barang reguler no  13  dari total keseluruhan barang :  20
Barang reguler no  18  dari total keseluruhan barang :  20
Barang reguler no  7  dari total keseluruhan barang :  20
Barang reguler no  16  dari total keseluruhan barang :  20
Barang reguler no  6  dari total keseluruhan barang :  20
Barang reguler no  9  dari total keseluruhan barang :  20
Barang reguler no  15  dari total keseluruhan barang :  20
Barang Penunjang Sekolah
Barang Pokok Sekolah
Barang reguler no  17  dari total keseluruhan barang :  20
Barang reguler no  8  dari total keseluruhan barang :  20
Barang reguler no  3  dari total keseluruhan barang :  20
Barang reguler no  19  dari total keseluruhan barang :  20
Barang reguler no  1  dari total keseluruhan barang :  20
Barang reguler no  10  dari total keseluruhan barang :  20
Barang reguler no  5  dari total keseluruhan barang :  20
Barang reguler no  11  dari total keseluruhan barang :  20
Barang reguler no  14  dari total keseluruhan barang :  20
Barang reguler no

In [3]:
!mpiexec -n 10 python mpibagikerja.py

File (rank) 2 merekap barang nomor 40 60 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59] 20 dari 200


File (rank) 3 merekap barang nomor 60 80 [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79] 20 dari 200


File (rank) 7 merekap barang nomor 140 160 [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159] 20 dari 200


File (rank) 1 merekap barang nomor 20 40 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39] 20 dari 200


File (rank) 5 merekap barang nomor 100 120 [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119] 20 dari 200


File (rank) 8 merekap barang nomor 160 180 [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179] 20 dari 200


File (rank) 9 merekap barang nomor 180 200 [180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,

In [4]:
!mpiexec -n 10 python sendrecv_simple.py

File(rank) 3  Tidak merekap
File(rank) 8  Tidak merekap
File(rank) 4  Tidak merekap
File(rank) 7  Tidak merekap
File(rank) 9  Tidak merekap
File(rank) 0  mengirim barang
File(rank) 1  menerima : 45   barang reguler
File(rank) 5  Tidak merekap
File(rank) 2  menerima : barang pokok sekolah 
File(rank) 6  Tidak merekap


In [5]:
!mpiexec -n 10 python sendrecv_next.py

File (rank) 9  Tidak merekap
File (rank) 3  Tidak merekap
File (rank) 7  Tidak merekap
File (rank) 6  Tidak merekap
File (rank) 4  Tidak merekap
File (rank) 8  Tidak merekap
File (rank) 0  mengirim data barang
File (rank) 5  Tidak merekap
File (rank) 1  menerima  c: 10 barang kebutuhan sekolah
			 d: [2, 3, 4] (nomor barang tertentu)
File (rank) 2  menerima c: 10  barang kebutuhan sekolah


In [6]:
!mpiexec -n 10 python sendrecv_adv1.py

File (rank) 9  Tidak Merekap
File (rank) 6  Tidak Merekap
File (rank) 5  Tidak Merekap
File (rank) 8  Tidak Merekap
File (rank) 1  Hasil Sementara : 10000000 
File (rank) 2  Hasil Sementara : 2000000 
File (rank) 3  Hasil Akhir : 60000000 
File (rank) 7  Tidak Merekap
File (rank) 4  Hasil Akhir : 12000000 
File (rank) 0  mengirim rincian data barang
Hasil sendrecv total =  132000000


In [7]:
!mpiexec -n 10 python sendrecv_adv2.py

File(rank) 0  mengirim data barang ke  1  2  3  4  5  6  7  8  9  
File(rank) 1   :  send  2 15 | recv  2 40 | send  4 15 | recv  4 80 | send  6 15 | recv  6 120 | send  8 15 | recv  8 160 | 
File(rank) 2   :  | send  1 40 | recv  1 30 | send  3 40 | recv  3 90 | send  5 40 | recv  5 150 | send  7 40 | recv  7 210 | send  9 40 | recv  9 270 | 
File(rank) 3   :  send  2 45 | recv  2 120 | send  4 45 | recv  4 240 | send  6 45 | recv  6 360 | send  8 45 | recv  8 480 | 
File(rank) 5   :  send  2 75 | recv  2 200 | send  4 75 | recv  4 400 | send  6 75 | recv  6 600 | send  8 75 | recv  8 800 | 
File(rank) 4   :  | send  1 80 | recv  1 60 | send  3 80 | recv  3 180 | send  5 80 | recv  5 300 | send  7 80 | recv  7 420 | send  9 80 | recv  9 540 | 
File(rank) 6   :  | send  1 120 | recv  1 90 | send  3 120 | recv  3 270 | send  5 120 | recv  5 450 | send  7 120 | recv  7 630 | send  9 120 | recv  9 810 | 
File(rank) 7   :  send  2 105 | recv  2 280 | send  4 105 | recv  4 560 | send  6 105

In [8]:
!mpiexec -n 10 python broadcast.py

cetak 1 rank 6 memiliki jumlah data1 : 0 
cetak 1 rank 6 memiliki jumlah data2 : 0 
cetak 1 rank 9 memiliki jumlah data1 : 0 
cetak 1 rank 9 memiliki jumlah data2 : 0 
cetak 1 rank 3 memiliki jumlah data1 : 0 
cetak 1 rank 3 memiliki jumlah data2 : 0 
cetak 1 rank 1 memiliki jumlah data1 : 0 
cetak 1 rank 1 memiliki jumlah data2 : 0 
cetak 1 rank 5 memiliki jumlah data1 : 0 
cetak 1 rank 5 memiliki jumlah data2 : 0 
cetak 1 rank 0 memiliki jumlah data1 : 10 
cetak 1 rank 0 memiliki jumlah data2 : 20 
cetak 1 rank 7 memiliki jumlah data1 : 0 
cetak 1 rank 8 memiliki jumlah data1 : 0 
cetak 1 rank 7 memiliki jumlah data2 : 0 
cetak 1 rank 8 memiliki jumlah data2 : 0 
cetak 1 rank 2 memiliki jumlah data1 : 15 
cetak 1 rank 2 memiliki jumlah data2 : 5 
cetak 2 rank 2 memiliki jumlah data1 : 10 
cetak 2 rank 0 memiliki jumlah data1 : 10 
cetak 2 rank 2 memiliki jumlah data2 : 5 
cetak 2 rank 0 memiliki jumlah data2 : 5 
cetak 2 rank 3 memiliki jumlah data1 : 10 
cetak 2 rank 3 memiliki juml

In [9]:
!mpiexec -n 10 python broadcastmanual.py

cetak 1 rank 9 memiliki jumlah data3 : 0 
cetak 1 rank 7 memiliki jumlah data3 : 0 
cetak 1 rank 3 memiliki jumlah data3 : 0 
cetak 1 rank 5 memiliki jumlah data3 : 0 
cetak 1 rank 6 memiliki jumlah data3 : 0 
cetak 1 rank 8 memiliki jumlah data3 : 0 
cetak 1 rank 2 memiliki jumlah data3 : 0 
cetak 1 rank 0 memiliki jumlah data3 : 20 
cetak 1 rank 1 memiliki jumlah data3 : 0 
cetak 1 rank 4 memiliki jumlah data3 : 0 
cetak 2 rank 6 memiliki jumlah data3 : 0 
cetak 2 rank 1 memiliki jumlah data3 : 0 
cetak 2 rank 7 memiliki jumlah data3 : 0 
cetak 2 rank 5 memiliki jumlah data3 : 0 
cetak 2 rank 2 memiliki jumlah data3 : 20 
cetak 2 rank 9 memiliki jumlah data3 : 0 
cetak 2 rank 8 memiliki jumlah data3 : 0 
cetak 2 rank 0 memiliki jumlah data3 : 20 
cetak 2 rank 4 memiliki jumlah data3 : 20 
cetak 2 rank 3 memiliki jumlah data3 : 20 
cetak 3 rank 1 memiliki jumlah data4 : 5 
cetak 3 rank 9 memiliki jumlah data4 : 5 
cetak 3 rank 5 memiliki jumlah data4 : 5 
cetak 3 rank 2 memiliki jumla

In [10]:
!mpiexec -n 10 python broadcast_adv.py

cetak 4 rank 6 memiliki data5 : 1 
cetak 4 rank 8 memiliki data5 : 1 
cetak 5 rank 8 memiliki data6 : 0 
cetak 4 rank 1 memiliki data5 : 15 
cetak 4 rank 3 memiliki data5 : 15 
cetak 5 rank 3 memiliki data6 : 0 
cetak 4 rank 5 memiliki data5 : 15 
cetak 5 rank 5 memiliki data6 : 0 
cetak 4 rank 2 memiliki data5 : 1 
cetak 5 rank 2 memiliki data6 : 0 
cetak 4 rank 0 memiliki data5 : 15 
cetak 4 rank 7 memiliki data5 : 15 
cetak 5 rank 7 memiliki data6 : 0 
cetak 5 rank 1 memiliki data6 : 10 
cetak 4 rank 4 memiliki data5 : 1 
cetak 5 rank 4 memiliki data6 : 0 
cetak 4 rank 9 memiliki data5 : 15 
cetak 5 rank 9 memiliki data6 : 0 
cetak 5 rank 0 memiliki data6 : 10 
cetak 5 rank 6 memiliki data6 : 10 


In [11]:
!mpiexec -n 10 python scatter_simple.py

rank 1 data :  1
rank 2 data :  2
rank 3 data :  3
rank 8 data :  8
rank 0 data :  0
rank 9 data :  9
rank 4 data :  4
rank 5 data :  5
rank 6 data :  6
rank 7 data :  7


In [12]:
!mpiexec -n 10 python scatter_split.py

rank 6 data :  [12 13]
rank 1 data :  [2 3]
rank 0 data :  [0 1]
rank 7 data :  [14 15]
rank 9 data :  [18 19]
rank 5 data :  [10 11]
rank 8 data :  [16 17]
rank 3 data :  [6 7]
rank 4 data :  [8 9]
rank 2 data :  [4 5]


In [13]:
!mpiexec -n 10 python scatter_manual_bagikerja.py

rank 1 data :  [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
rank 2 data :  [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
rank 4 data :  [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
rank 3 data :  [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
rank 6 data :  [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
rank 5 data :  [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
rank 8 data :  [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]
rank 7 data :  [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]
rank 0 data :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
rank 9 data :  [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [14]:
!mpiexec -n 10 python scatter_numpy.py

rank 8 menerima data barang [8 8 8 8 8 8 8 8 8 8] 
rank 0 menerima data barang [0 0 0 0 0 0 0 0 0 0] 
rank 4 menerima data barang [4 4 4 4 4 4 4 4 4 4] 
rank 9 menerima data barang [9 9 9 9 9 9 9 9 9 9] 
rank 2 menerima data barang [2 2 2 2 2 2 2 2 2 2] 
rank 5 menerima data barang [5 5 5 5 5 5 5 5 5 5] 
rank 3 menerima data barang [3 3 3 3 3 3 3 3 3 3] 
rank 6 menerima data barang [6 6 6 6 6 6 6 6 6 6] 
rank 1 menerima data barang [1 1 1 1 1 1 1 1 1 1] 
rank 7 menerima data barang [7 7 7 7 7 7 7 7 7 7] 


In [15]:
!mpiexec -n 10 python scatter_alltoall.py

rank 0 recvdata :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] -->(barang kelipatan 0)
rank 4 recvdata :  [ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40.] -->(barang kelipatan 4)
rank 7 recvdata :  [ 7. 14. 21. 28. 35. 42. 49. 56. 63. 70.] -->(barang kelipatan 7)
rank 1 recvdata :  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] -->(barang kelipatan 1)
rank 8 recvdata :  [ 8. 16. 24. 32. 40. 48. 56. 64. 72. 80.] -->(barang kelipatan 8)
rank 6 recvdata :  [ 6. 12. 18. 24. 30. 36. 42. 48. 54. 60.] -->(barang kelipatan 6)
rank 5 recvdata :  [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.] -->(barang kelipatan 5)
rank 9 recvdata :  [ 9. 18. 27. 36. 45. 54. 63. 72. 81. 90.] -->(barang kelipatan 9)
rank 2 recvdata :  [ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.] -->(barang kelipatan 2)
rank 3 recvdata :  [ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30.] -->(barang kelipatan 3)


In [16]:
!mpiexec -n 10 python gather.py

rank 3 mengirim [3 3 3 3 3 3 3 3 3 3]
rank 3 menerima None
rank 1 mengirim [1 1 1 1 1 1 1 1 1 1]
rank 1 menerima None
rank 7 mengirim [7 7 7 7 7 7 7 7 7 7]
rank 7 menerima None
rank 5 mengirim [5 5 5 5 5 5 5 5 5 5]
rank 5 menerima None
rank 2 mengirim [2 2 2 2 2 2 2 2 2 2]
rank 2 menerima None
rank 6 mengirim [6 6 6 6 6 6 6 6 6 6]
rank 6 menerima None
rank 9 mengirim [9 9 9 9 9 9 9 9 9 9]
rank 9 menerima None
rank 4 mengirim [4 4 4 4 4 4 4 4 4 4]
rank 4 menerima None
rank 8 mengirim [8 8 8 8 8 8 8 8 8 8]
rank 8 menerima None
rank 0 mengirim [0 0 0 0 0 0 0 0 0 0]
rank 0 menerima [[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]


In [17]:
!mpiexec -n 10 python gather_simple.py

[rank, 20*rank, jumlahbarang]
<class 'list'>
[[0, 0, 20], [1, 20, 20], [2, 40, 20], [3, 60, 20], [4, 80, 20], [5, 100, 20], [6, 120, 20], [7, 140, 20], [8, 160, 20], [9, 180, 20]]


In [18]:
!mpiexec -n 10 python gatheralt.py

file 1 mendapatkan (menerima) data dari rank : None 
file 3 mendapatkan (menerima) data dari rank : None 
file 9 mendapatkan (menerima) data dari rank : None 
file 7 mendapatkan (menerima) data dari rank : None 
file 8 mendapatkan (menerima) data dari rank : None 
file 5 mendapatkan (menerima) data dari rank : None 
file 2 mendapatkan (menerima) data dari rank : None 
file 6 mendapatkan (menerima) data dari rank : None 
file 4 mendapatkan (menerima) data dari rank : None 
file 0 mendapatkan (menerima) data dari rank : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 


In [19]:
!mpiexec -n 20 python reduce.py

Jumlah keseluruhan pengiriman data (rank 0) SUM :  210
Nilai Rata-rata Jumlah perekapan data (rank 0) MEAN :  10.5
Nilai MIN keseluruhan pengiriman data (rank 0) MIN :  1
Nilai MAX keseluruhan pengiriman data (rank 0) MAX :  20
Nilai perkalian keseluruhan data rank 0 PROD :  2432902008176640000
Nilai pengiriman data terbesar dan rank-nya 0 MAXLOC :  (19, 140)
Nilai pengiriman data terkecil dan rank-nya 0 MINLOC :  (0, 17)


In [20]:
!mpiexec -n 10 python reducearray.py

file (rank 0) SUM :  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
file (rank 0) MIN :  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
file (rank 0) MAX :  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]


In [21]:
!mpiexec -n 10 python reduce_logic.py

rank 9 data :  True
rank 8 data :  True
rank 7 data :  True
rank 6 data :  True
rank 2 data :  False
rank 3 data :  False
rank 5 data :  False
rank 4 data :  False
rank 1 data :  False
rank 0 data :  False
file root (rank) 0 LAND :  False
file root (rank) 0 LOR :  True
file root (rank) 0 BAND :  False
file root (rank) 0 BOR :  True


In [22]:
!mpiexec -n 10 python allreduce.py

rank 3 menerima data :  100 data
rank 5 menerima data :  100 data
rank 4 menerima data :  100 data
rank 2 menerima data :  100 data
rank 8 menerima data :  100 data
rank 0 menerima data :  100 data
rank 1 menerima data :  100 data
rank 6 menerima data :  100 data
rank 9 menerima data :  100 data
rank 7 menerima data :  100 data


In [23]:
#reduce-scatter
!mpiexec -n 10 python reducescatter.py

file (rank 9) senddata barang :  [  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350
 360 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530
 540 550 560 570 580 590]
file (rank 9) recvdata barang :  [2970 3025 3080 3135 3190 3245]


file (rank 8) senddata barang :  [  0   9  18  27  36  45  54  63  72  81  90  99 108 117 126 135 144 153
 162 171 180 189 198 207 216 225 234 243 252 261 270 279 288 297 306 315
 324 333 342 351 360 369 378 387 396 405 414 423 432 441 450 459 468 477
 486 495 504 513 522 531]
file (rank 8) recvdata barang :  [2640 2695 2750 2805 2860 2915]


file (rank 5) senddata barang :  [  0   6  12  18  24  30  36  42  48  54  60  66  72  78  84  90  96 102
 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 204 210
 216 222 228 234 240 246 252 258 264 270 276 282 288 294 300 306 312 318
 324 330 336 342 348 354]
file (rank 5) recvdata barang : 